-
  alias: 'Lights on for when Ceri gets home'
  trigger:
    platform: time
    at: '17:30:00'
  condition:
    condition: state
    entity_id: 'binary_sensor.workday_sensor'
    state: 'on'
  action:
    service: switch.turn_on
    entity_id: group.living_room_lights

-
  alias: 'Morning Daystar on'
  trigger:
    platform: time
    at: '09:00:00'
  condition:
    condition: state
    entity_id: 'binary_sensor.workday_sensor'
    state: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.daystar

-
  alias: 'Afternoon Daystar off'
  trigger:
    platform: time
    at: '13:00:00'
  action:
    service: switch.turn_off
    entity_id: switch.daystar

-
  alias: 'Front lamp on for Ceri in the morning'
  trigger:
    platform: time
    at: '05:50:00'
  condition:
    condition: state
    entity_id: 'binary_sensor.workday_sensor'
    state: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.front_lamp

-
  alias: 'Front lamp off once the sun is up'
  trigger:
    platform: sun
    event: sunrise
    offset: '+01:00:00'
  action:
    service: switch.turn_off
    entity_id: switch.front_lamp

-
  alias: 'Front lamp on before sunset'
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'
  action:
    service: switch.turn_on
    entity_id: switch.front_lamp

-
  alias: "Let me know on Slack if there's motion detected"
  trigger:
    platform: event
    event_type: motion.on_event_start
  action:
    service: notify.slack
    data_template:
      message: "Motion detected: {{ trigger.event.data.get('hostname', 'Device unknown') }}"

-
  alias: "Away mode: Lights on before sunset"
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'
  condition:
    condition: state
    entity_id: input_boolean.away_mode
    state: 'on'
  action:
    - service: script.gradual_lights_on

-
  alias: "Away mode: Lights off at night"
  trigger:
    platform: time
    at: '23:32:23'
  condition:
    condition: state
    entity_id: input_boolean.away_mode
    state: 'on'
  action:
    - service: script.gradual_lights_off
